### ISSUE TITLE
Line endings are not automatically converted to Unix style when pasting

### ISSUE THREAD

**Issue by smathot** [smathot/QProgEdit#19]
When text is pasted into the editor, then line endings are encoded as they are on the system. Instead, they should be converted to Unix style.

**Comment by smathot** [comment]
This related to smathot/python-qdatamatrix#3. See also:

- http://forum.cogsci.nl/index.php?p=/discussion/2592/

In general, copy-pasting to editor components (QProgEdit) and tables (QDataMatrix) doesn't work on Mac OS. At least part of the problem seems to be incorrect line-ending conversions.

**Comment by dschreij** [comment]
Hopefully, https://github.com/smathot/QProgEdit/pull/20 fixes this.
