### ISSUE TITLE
Word wrap cannot be turned off per default

### ISSUE THREAD

**Issue by eort** [smathot/QProgEdit#21]
Hi, 

Normally, when a setting of the `inline_script` is (un)checked Opensesame will remember the changes and use them the next time it is started. The `wordwrap` setting is not, though. Every time you boot Opensesame, the vertical line is drawn at 80 characters. 

I tried to hardcode the default to be "do not draw any line" in `QProgEdit/_qeditorcfg.py`, but changing the lines
~~~.python
self.qProgEditWordWrapMarker = 80
self.qProgEditWordWrap = True
~~~
to
~~~.python
self.qProgEditWordWrapMarker = None
self.qProgEditWordWrap = False
~~~
 had no effect. To induce any change to the default behaviour of the editor, I had to edit `QProgEdit/_qeditor.py` file directly. 

To be clear, removing the wordwrapping during a session, works perfectly fine, it is only the initial setting at start-up that does not behave as I expect it to. 

Eduard

**Comment by smathot** [comment]
Thanks for this. It was a weird interaction between how OpenSesame handlesconfig info, and how QProgEdit does it. Essentially, OpenSesame doesn't allow one config option to have different types; and QProgEdit used `None` and `int` for `qProgEditWordWrapMarker`.

Should be fixed in 4.0.10.
